name: build Code

on:
  push:
    branches:
      - main
  pull_request:


env:
  CARGO_TERM_COLOR: always


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Run build
      - name: build_script
        run: cargo build 
